### ISSUE TITLE
SDL2_mixer.dll error

### ISSUE THREAD

**Issue by paulwalz** [VitoVan/focalizzare#3]
When I run the latest version of Focalizzare on my Windows 10 Pro 64x machine (with all Windows Updates installed) I get the following error message immediately:

"calm-app.exe - Entry Point Not Found
The procedure entry point SDL_RWclose could not be located in the dynamic link library C:\Focalizzare\calm-app-root\lib\SDL2_mixer.dll."

After I click "OK" to this error message the app immediately exits.

This error happens if I install the app at C:\Focalizzare, but also if I install it in the default location in my user's home directory. I only re-installed it here thinking that maybe the space in my Windows username might be causing the issue.

I confirmed that yes, that .dll file does exist at that location on my hard drive.
Also, I get this same error message for the latest version of the "Maze" app and the latest version of the "Pelusica" app - do you want me to recreate this bug ticket for those projects too?

The Calm project is really cool, thank you for taking the time to create it and release the code!

**Comment by VitoVan** [comment]
@paulwalz 

Thank you for posting this.

I will investigate this issue soon.



> The Calm project is really cool, thank you for taking the time to create it and release the code!

Thank you very much for this compliment, the occasionally occurred words like this tortured me to keep working on CALM project.

**Comment by VitoVan** [comment]
By the first glance, I suppose you have custom installed SDL in your PATH env.

**Comment by paulwalz** [comment]
@VitoVan I have done some testing regarding having a custom SDL in my PATH env.

If I open a cmd.exe prompt and to the following...

Items entered at command prompt BEGIN -----------------------------------
; This generates the error message that this issue is reporting:
"C:\Focalizzare\calm-app-root\calm.exe"

; This shows many paths. There are many:
echo %PATH%

; This sets my PATH env var to be undefined so that the PATH env var doesn't contain paths to be searched:
set PATH=

; This confirms that the PATH env var is in fact undefined now as desired:
echo %PATH%

; This now successfully runs Focalizzare!
C:\Focalizzare\calm-app-root>calm.exe
Items entered at command prompt END -----------------------------------

In other words, Focalizzare (and Maze, and Pelusica) all successfully launch *if and only if* the PATH env var is undefined. I could probably remove only those PATH entries that are causing the issue for Focalizzare but it was difficult to track down which paths were actually causing the issue so I just set the PATH to be undefined.

(Side notes: 1) Maze and Pelusica both crash soon after launching them if I launch them from the command prompt by running "PATH-TO-APP\calm-app-root\calm.exe" from the root of the drive. If I instead change to the directory that the app lives in using "cd PATH-TO-APP\calm-app-root\" and then run "calm.exe" they do not crash. This issue might also affect Focalizzare and the main Calm app. I don't know if you consider this an issue worth pursuing or not. 2) Also, when dragging your apps from a monitor with one DPI setting to another monitor with a different DPI setting the app's window does strange resizing things until you release the mouse button and then they fix themselves - another issue that I don't know if you will consider worth pursuing but I thought I would mention it.)

The PATH issue begs the question though... the main Calm application (from https://vitovan.com/calm/) works *without* setting my PATH env var to be empty. So, shouldn't Focalizzare, Maze, and Pelusica *also* work without setting my PATH env var to be empty? Doesn't this mean that the main Calm app is doing something *good* that ought to be propagated to your other apps?

**Comment by VitoVan** [comment]
Thank you very much for your efforts!

> The PATH issue begs the question though... the main Calm application (from https://vitovan.com/calm/) works without setting my PATH env var to be empty. So, shouldn't Focalizzare, Maze, and Pelusica also work without setting my PATH env var to be empty? Doesn't this mean that the main Calm app is doing something good that ought to be propagated to your other apps?

You are right:

The current Focalizzare was bundled with CALM 1.1.0

https://github.com/VitoVan/focalizzare/blob/43b0654c12ba39bb3ebe3a7a038b8ed45e28caa0/.github/workflows/build.yml#L90

And the latest CALM is: 1.2.0

https://github.com/VitoVan/calm/releases/tag/1.2.0

Related issue:

https://github.com/VitoVan/calm/issues/170

**Comment by paulwalz** [comment]
@VitoVan I took a look at the related issue [VitoVan/calm#170](https://github.com/VitoVan/calm/issues/170) and the associated code updates, very interesting reading. If I understand correctly the issue is that the 1.2.0 version of Calm *appended* the path to the PATH environment variable when the path needs to be *prepended* in order to take precedence. That issue is fixed in the current release of the main Calm app which is why Calm works on my computer. Thank you for pointing me in the right direction :)

I think it is common for people to have other versions of SDL in their PATH on Windows so as it stands Focalizzare, Maze and Pelusica will be broken for those people. Will you have time to cut new releases of those apps soon?

Thanks

**Comment by VitoVan** [comment]
> I think it is common for people to have other versions of SDL in their PATH on Windows so as it stands Focalizzare, Maze and Pelusica will be broken for those people. Will you have time to cut new releases of those apps soon?

Since you asked, I think I should update these applications as soon as possible, maybe less than a week.

I hope I can keep my promise.

Thank you again for your time and persistence. I would have given up on a buggy software like this if I were you.

**Comment by paulwalz** [comment]
> Since you asked, I think I should update these applications as soon as possible, maybe less than a week.

Thank you @VitoVan I am really looking forward to using your apps, especially Focalizzare :)

> Thank you again for your time and persistence. I would have given up on a buggy software like this if I were you.

Honestly I just love being able to use Common Lisp apps on Windows. There are so few CL apps for Windows, especially with GUIs!

**Comment by VitoVan** [comment]
@paulwalz Hello there, I tried Focalizzare 1.1.1 with different versions of SDL2 and SDL2_mixer in the PATH, without reproducing the problem you mentioned here, could you please let me know the version of SDL2 related libs in your PATH?

Anyway, I upgraded Focalizzare to 1.1.2 in a pre-release:

https://github.com/VitoVan/focalizzare/releases/tag/1.1.2

If you don't mind, please help testing this and let me know if it worked for your scenario.

Thanks for your patience and faith in Common Lisp.

**Comment by paulwalz** [comment]
> @paulwalz Hello there, I tried Focalizzare 1.1.1 with different versions of SDL2 and SDL2_mixer in the PATH, without reproducing the problem you mentioned here, could you please let me know the version of SDL2 related libs in your PATH?

Hi @VitoVan, I ran the following code:

```
(defun find-file-in-directories-that-are-in-the-PATH-env-var (filename)
  "Find the supplied file in the directories that are defined in the PATH environment variable. Return list of directory paths or nil."

  (loop with path = (uiop:getenv "PATH")
        for p in (uiop:split-string path :separator ";")
        for dir = (probe-file p)
          when (and (uiop:directory-exists-p dir) (uiop:file-exists-p (merge-pathnames filename dir)))
        collect dir))

(find-file-in-directories-that-are-in-the-PATH-env-var "sdl2.dll") ; --> ("C:/Program Files/qemu/")
(find-file-in-directories-that-are-in-the-PATH-env-var "SDL2_mixer.dll") ; --> NIL
(find-file-in-directories-that-are-in-the-PATH-env-var "libjxl.dll") ; --> NIL
(find-file-in-directories-that-are-in-the-PATH-env-var "libLerc.dll") ; --> ("C:/Program Files/Tesseract-OCR/")
```

I used find-file-in-directories-that-are-in-the-PATH-env-var to find the file that Focalizzare was complaining about. Then I would remove the returned directory that the file was found in from the PATH environment variable, run Focalizzare again to find out what the next problem file is and repeat the process.

In terms of the versions of the files... if I right click on the file and choose Properties and then click on the Details tab I see the following: 
C:/Program Files/qemu/sdl2.dll has a File Version of 2.0.7.0
C:/Program Files/Tesseract-OCR/libLerc.dll has a File Version that is empty (i.e. not set). I don't think libLerc.dll nor libjxl.dll are a part of SDL2 but I thought I would mention them since they are mentioned in the error messages.

Is that the information you need? If you need some additional information please let me know.

> Anyway, I upgraded Focalizzare to 1.1.2 in a pre-release:
>
> https://github.com/VitoVan/focalizzare/releases/tag/1.1.2
>
> If you don't mind, please help testing this and let me know if it worked for your scenario.

I tried Focalizzare 1.1.2 Pre-release and it works beautifully. I no longer receive any error messages and everything functions as expected. Thank you for issuing a fixed version :)

> Thanks for your patience and faith in Common Lisp.

Of course, it is always good fun!

**Comment by VitoVan** [comment]
@paulwalz 

Hi there, thank you very much for your feedback, it helped a lot.

Now I have upgraded all the applications you mentioned to the latest CALM 1.3.1, here you can download and play with them directly:

The Maze:

https://github.com/VitoVan/lisp-game-jam-2023/releases/download/spring-0.1.0/Maze-Installer.exe

Pelúsica:

https://github.com/VitoVan/pelusica/releases/download/1.1.0/Pelusica.exe

And now CALM supports the latest macOS Sonoma on Apple Silicon chips, if you have any fancy friends running that OS and telling you Lisp is too old to play with, you can just slap them with CALM made applications.

Have fun and prosper! 🖖

**Comment by paulwalz** [comment]
Hi @VitoVan,

> Hi there, thank you very much for your feedback, it helped a lot.

You're welcome :)

> Now I have upgraded all the applications you mentioned to the latest CALM 1.3.1, here you can download and play with them directly:

I have tested the new versions of Maze and Pelusica and they both work correctly now.

Thank you!
